name: Deploy backend

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the docker image
        run: docker build -t saulgoodman13/node-backend .
      - name: Publish to dockerhub
        run: docker push saulgoodman13/node-backend:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from dockerhub
        run: docker pull saulgoodman13/node-backend:latest
      - name: Run docker container
        run: docker run -p 4000:8000 \
            --name nodejs-app-container \
            -e MONGO_URI='${{ secrets.MONGO_URI }}' \
            -e DB_NAME='${{ secrets.DB_NAME }}' \
            -e JWT_TOKEN_SECRET='${{ secrets.JWT_TOKEN_SECRET }}' \
            -e JWT_TOKEN_EXPIRY='${{ secrets.JWT_TOKEN_EXPIRY }}' \
            saulgoodman13/node-backend